server:
  port: 9001
  
spring:
   datasource:
      url: jdbc:mysql://localhost:5432/JS-Jobs
      driver-class-name:  com.mysql.jdbc.Driver
      username: root
      password: Ashok@777
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
   application:
      name: advertise-service
     
eureka:
  client:    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}     
    